#!/usr/bin/env python3
"""
Images & Tables shared-ingestion profile runner.

Dry-run emits normalized image/table chunks and lightweight attachment-first
cards (no Gemini, no semantic generation — useful as a sanity check).

Live mode (`--mode generate`, v4.56) emits normalized chunks first, then
delegates to `tools/images-tables-question-generator/generate_images_tables_questions.py`
to run real per-image Gemini classification + NBME-style question generation.
Image placement follows the canonical rule set: diagnostic images go in the
stem when interpretation is needed; explanation-only images and ALL tables go
in the answer explanation.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import json
import mimetypes
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from chunk_pipeline import run_shared_chunk_pipeline
from recovery_contract import recovery_metadata


RUNNER_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = RUNNER_DIR.parents[1]
JOB_OUTPUT_ROOT = Path(os.environ["BIC_JOB_OUTPUT_ROOT"]).expanduser().resolve() if os.environ.get("BIC_JOB_OUTPUT_ROOT") else None
OUTPUT_DIR = JOB_OUTPUT_ROOT / "shared-ingestion" if JOB_OUTPUT_ROOT else RUNNER_DIR / "output"
APP_READY_DIR = (
    JOB_OUTPUT_ROOT / "images-tables-question-generator" / "output_json" / "app_ready"
    if JOB_OUTPUT_ROOT else PROJECT_ROOT / "tools" / "images-tables-question-generator" / "output_json" / "app_ready"
)
IMAGES_TABLES_GENERATOR = PROJECT_ROOT / "tools" / "images-tables-question-generator" / "generate_images_tables_questions.py"
SOURCE_TYPE = "images_tables_source"
OUTPUT_SCHEMA_VERSION = "nbme-internal-app-ready-v2"
LABELS = ["A", "B", "C", "D"]
SUPPORTED_IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}


def emit(event_type: str, **payload: Any) -> None:
    event = {
        "type": event_type,
        "timestamp": dt.datetime.now(dt.timezone.utc).isoformat(),
        **payload,
    }
    print(json.dumps(event, ensure_ascii=False), flush=True)


def now_stamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d_%H%M%S")


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def mime_for(path: Path) -> str:
    return mimetypes.guess_type(path.name)[0] or "application/octet-stream"


def data_url(path: Path) -> str:
    mime = mime_for(path)
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def resolve_project_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def first_image_ref(chunk: dict[str, Any]) -> dict[str, Any]:
    refs = chunk.get("imageRefs") if isinstance(chunk.get("imageRefs"), list) else []
    for ref in refs:
        if isinstance(ref, dict):
            return ref
    return {}


def first_table_ref(chunk: dict[str, Any]) -> dict[str, Any]:
    refs = chunk.get("tableRefs") if isinstance(chunk.get("tableRefs"), list) else []
    for ref in refs:
        if isinstance(ref, dict):
            return ref
    return {}


def classification_label(kind: str) -> str:
    labels = {
        "table_image": "table",
        "algorithm": "algorithm",
        "chart": "chart",
        "stem_image": "image",
        "explanation_image": "image",
        "unknown": "image",
    }
    return labels.get(kind, "image")


def build_lightweight_question(chunk: dict[str, Any], index: int, bundle: dict[str, Any]) -> dict[str, Any]:
    image_ref = first_image_ref(chunk)
    table_ref = first_table_ref(chunk)
    kind = str(image_ref.get("kind") or chunk.get("metadata", {}).get("assetKind") or "unknown")
    asset_path = str(image_ref.get("path") or table_ref.get("path") or "")
    resolved_asset = resolve_project_path(asset_path)
    if not asset_path or not resolved_asset.exists():
        raise FileNotFoundError(f"Q{index}: asset file not found for chunk {chunk.get('chunkId')}: {asset_path}")
    ocr_text = str(chunk.get("text") or image_ref.get("text") or "").strip()
    asset_label = classification_label(kind)
    stem = (
        f"Review the attached {asset_label}. Which statement best describes the source asset preserved by this Images & Tables import card?"
    )
    if ocr_text:
        stem += f"\n\nOCR text preserved for review: {ocr_text[:600]}"
    choices = [
        {"l": "A", "t": "This card preserves the source asset and OCR/provenance for app review."},
        {"l": "B", "t": "This card was generated by advanced semantic medical reasoning."},
        {"l": "C", "t": "This card intentionally discards the original image after import."},
        {"l": "D", "t": "This card bypasses the app-ready JSON import pathway."},
    ]
    image_entry = {
        "figureKey": None,
        "dataUrl": data_url(resolved_asset),
        "isLabTable": kind == "table_image" or chunk.get("chunkType") == "table",
        "kind": "figure",
        "source": "images-tables-shared-ingestion",
        "originalFileName": chunk.get("metadata", {}).get("originalFileName") or resolved_asset.name,
        "assetPath": asset_path,
        "classification": kind,
        "stimulusType": kind,
        "placement": "stem",
        "attachmentConfidence": chunk.get("metadata", {}).get("attachmentConfidence"),
    }
    explanation = (
        "This is an attachment-first validation card. It proves that the normalized image/table asset, OCR text, "
        "and provenance can become an app-ready question and survive import."
    )
    answer_choices = [{"label": item["l"], "text": item["t"]} for item in choices]
    provenance = {
        "sourceType": SOURCE_TYPE,
        "sourceFormat": "images-tables-shared-ingestion",
        "sourceMode": "shared_normalized_chunks",
        "bundleSourcePath": bundle.get("sourcePath"),
        "chunkId": chunk.get("chunkId"),
        "chunkType": chunk.get("chunkType"),
        "assetKind": kind,
        "classificationReason": chunk.get("metadata", {}).get("classificationReason"),
        "attachmentConfidence": chunk.get("metadata", {}).get("attachmentConfidence"),
        "ocrTextAvailable": bool(ocr_text),
        "figureAttachments": {},
    }
    return {
        "id": f"images_tables_profile_{index:03d}_{chunk.get('chunkId')}",
        "questionNumber": index,
        "sourceQuestionNumber": index,
        "stem": stem,
        "answerChoices": answer_choices,
        "correctAnswer": "A",
        "explanationSections": [{"heading": "Attachment Validation", "body": [explanation]}],
        "hasEmbeddedFigure": False,
        "figureRefs": [],
        "tables": [],
        "extractionWarnings": list(chunk.get("warnings") or []),
        "n": index,
        "t": stem,
        "o": choices,
        "c": "A",
        "explanation": explanation,
        "correctBlurb": explanation,
        "e": {},
        "tags": [f"images-tables-{kind}"],
        "retrievalTag": f"images-tables-{kind}",
        "reviewPearl": "Attachment-first card preserving image/table source material for review.",
        "educationalObjective": "Validate image/table attachment preservation and rendering before semantic generation.",
        "images": [image_entry],
        "explanationImages": [],
        "metadata": provenance,
    }


def build_app_ready_payload(bundle: dict[str, Any], input_path: Path) -> dict[str, Any]:
    questions = [
        build_lightweight_question(chunk, index, bundle)
        for index, chunk in enumerate(bundle.get("chunks") or [], start=1)
        if isinstance(chunk, dict)
    ]
    if not questions:
        raise ValueError("No normalized chunks available for app-ready card generation.")
    return {
        "schemaVersion": OUTPUT_SCHEMA_VERSION,
        "name": f"Images Tables Shared Ingestion {now_stamp()}",
        "sourceFormat": "images-tables-shared-ingestion",
        "expectedQuestionCount": len(questions),
        "actualExtractedQuestionCount": len(questions),
        "imageAttachmentStrategy": "Attachment-first q.images[] cards persisted through FigureStore.",
        "metadata": {
            "sourceType": SOURCE_TYPE,
            "sourcePath": str(input_path),
            "normalizedChunkPath": "",
            "generationStyle": "attachment_first",
        },
        "generationWarnings": list(bundle.get("warnings") or []),
        "questions": questions,
    }


def validate_app_ready_payload(payload: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    questions = payload.get("questions")
    if not isinstance(questions, list) or not questions:
        return ["No questions were generated."]
    for index, question in enumerate(questions, start=1):
        prefix = f"Q{index}"
        if question.get("questionNumber") != index:
            errors.append(f"{prefix}: invalid questionNumber.")
        if not question.get("stem") or not question.get("t"):
            errors.append(f"{prefix}: missing stem.")
        if not isinstance(question.get("answerChoices"), list) or len(question["answerChoices"]) != 4:
            errors.append(f"{prefix}: answerChoices must contain four choices.")
        if not isinstance(question.get("o"), list) or len(question["o"]) != 4:
            errors.append(f"{prefix}: compact choices must contain four choices.")
        if question.get("correctAnswer") != "A" or question.get("c") != "A":
            errors.append(f"{prefix}: expected correct answer A.")
        images = question.get("images")
        if not isinstance(images, list) or len(images) != 1:
            errors.append(f"{prefix}: expected exactly one stem image.")
        elif not images[0].get("dataUrl") or not images[0].get("assetPath"):
            errors.append(f"{prefix}: image is missing dataUrl or assetPath.")
    return errors


def classification_summary(bundle: dict[str, Any]) -> dict[str, int]:
    summary: dict[str, int] = {}
    for chunk in bundle.get("chunks") or []:
        if not isinstance(chunk, dict):
            continue
        kind = str(chunk.get("metadata", {}).get("assetKind") or "unknown")
        summary[kind] = summary.get(kind, 0) + 1
    return summary


def discover_input_files(input_path: Path) -> list[Path]:
    if input_path.is_file():
        return [input_path]
    if not input_path.is_dir():
        return []
    files = []
    for path in sorted(input_path.iterdir()):
        if path.name.startswith(".") or not path.is_file():
            continue
        if path.suffix.lower() in SUPPORTED_IMAGE_EXTS:
            files.append(path)
    return files


def run_images_tables_generator_live(input_path: Path, output_root: Path) -> dict[str, Any]:
    files = discover_input_files(input_path)
    if not files:
        raise FileNotFoundError(f"No supported image files found at: {input_path}")

    app_ready_dir = output_root / "app_ready"
    app_ready_dir.mkdir(parents=True, exist_ok=True)
    per_file_outputs: list[Path] = []
    per_file_errors: list[str] = []

    for file_index, image_file in enumerate(files, start=1):
        emit(
            "images_tables_downstream_file_start",
            inputFile=str(image_file),
            fileIndex=file_index,
            totalFiles=len(files),
        )
        command = [
            sys.executable,
            str(IMAGES_TABLES_GENERATOR),
            "--generate",
            "--input-file",
            str(image_file),
            "--output-dir",
            str(app_ready_dir),
        ]
        started_at = time.time()
        proc = subprocess.run(
            command,
            cwd=str(PROJECT_ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        runtime = round(time.time() - started_at, 3)
        if proc.stdout.strip():
            emit("images_tables_downstream_stdout", message=proc.stdout.strip()[-2000:], fileIndex=file_index)
        if proc.stderr.strip():
            emit("images_tables_downstream_stderr", message=proc.stderr.strip()[-2000:], fileIndex=file_index)
        if proc.returncode != 0:
            per_file_errors.append(f"{image_file.name}: exit {proc.returncode} ({proc.stderr.strip().splitlines()[-1] if proc.stderr.strip() else 'no stderr'})")
            emit(
                "images_tables_downstream_file_failed",
                inputFile=str(image_file),
                exitCode=proc.returncode,
                runtimeSeconds=runtime,
            )
            continue
        produced = sorted(app_ready_dir.glob("images_tables_*_app_ready.json"), key=lambda p: p.stat().st_mtime)
        recent = [p for p in produced if p.stat().st_mtime >= started_at - 1]
        if not recent:
            per_file_errors.append(f"{image_file.name}: generator returned 0 but no app-ready JSON discovered")
            emit(
                "images_tables_downstream_file_failed",
                inputFile=str(image_file),
                exitCode=0,
                runtimeSeconds=runtime,
                reason="missing app-ready output",
            )
            continue
        latest = recent[-1]
        per_file_outputs.append(latest)
        emit(
            "images_tables_downstream_file_complete",
            inputFile=str(image_file),
            outputPath=str(latest),
            runtimeSeconds=runtime,
        )
        # Small pause to avoid timestamp collisions in filenames produced by the generator.
        time.sleep(1)

    if not per_file_outputs:
        raise RuntimeError(
            "Images & Tables live generation produced no app-ready outputs. "
            + (per_file_errors[0] if per_file_errors else "See per-file events.")
        )

    combined_path = merge_per_image_outputs(per_file_outputs, app_ready_dir)
    emit(
        "images_tables_combined_app_ready",
        outputPath=str(combined_path),
        combinedQuestionCount=len(json.loads(combined_path.read_text(encoding="utf-8")).get("questions", [])),
        perImageOutputCount=len(per_file_outputs),
    )

    return {
        "outputRoot": str(output_root),
        "combinedAppReadyOutputPath": str(combined_path),
        "perImageOutputPaths": [str(p) for p in per_file_outputs],
        "filesAttempted": len(files),
        "filesSucceeded": len(per_file_outputs),
        "filesFailed": len(per_file_errors),
        "perFileErrors": per_file_errors,
    }


def merge_per_image_outputs(per_file_outputs: list[Path], app_ready_dir: Path) -> Path:
    """Combine one-question-per-image JSONs into a single combined app-ready JSON.

    BIC calls this runner once per input file, so a multi-file job invokes the
    runner N times. Each invocation:
      1) Renames its own fresh per-image outputs to *_per_image.json (so BIC's
         discover_outputs *_app_ready.json glob does not pick them up).
      2) Scans the entire app-ready directory for ALL *_per_image.json files
         (including ones from prior invocations in the same job).
      3) Writes a single stable-named combined file with all questions found.

    The stable filename means later invocations overwrite earlier combined files,
    so by the time the last input completes, exactly one combined app-ready JSON
    exists and contains every question generated for the job. BIC auto-import
    then loads it and imports the full set in one shot.
    """
    # Step 1: rename fresh per-image outputs so they fall outside BIC discovery.
    for path in per_file_outputs:
        if path.exists() and path.name.endswith("_app_ready.json"):
            renamed = path.with_name(path.name.removesuffix("_app_ready.json") + "_per_image.json")
            try:
                path.rename(renamed)
            except OSError:
                pass

    # Step 2: gather every per-image file in the directory (this invocation + prior).
    per_image_paths = sorted(app_ready_dir.glob("*_per_image.json"))
    if not per_image_paths:
        # Should not happen given step 1 just ran, but defend anyway.
        raise RuntimeError(f"No per-image outputs found in {app_ready_dir} to merge.")

    combined_questions: list[dict[str, Any]] = []
    combined_warnings: list[Any] = []
    source_format = "images-tables"
    schema_version = OUTPUT_SCHEMA_VERSION
    name_seed = ""
    for index, path in enumerate(per_image_paths, start=1):
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not name_seed:
            name_seed = str(payload.get("name") or "Images Tables Generated")
            source_format = str(payload.get("sourceFormat") or source_format)
            schema_version = str(payload.get("schemaVersion") or schema_version)
        for question in payload.get("questions") or []:
            if not isinstance(question, dict):
                continue
            renumbered = dict(question)
            renumbered["questionNumber"] = index
            renumbered["sourceQuestionNumber"] = index
            renumbered["n"] = index
            combined_questions.append(renumbered)
        combined_warnings.extend(payload.get("generationWarnings") or [])

    combined_payload = {
        "schemaVersion": schema_version,
        "name": name_seed or "Images Tables Generated",
        "sourceFormat": source_format,
        "expectedQuestionCount": len(per_image_paths),
        "actualExtractedQuestionCount": len(combined_questions),
        "imageAttachmentStrategy": "q.images[] for stem images; q.explanationImages[] for explanation images; both persisted through FigureStore",
        "generationWarnings": combined_warnings,
        "questions": combined_questions,
    }
    # Stable filename — later runner invocations in the same BIC job overwrite this,
    # so exactly one combined file exists in the job output root at completion.
    combined_path = app_ready_dir / "images_tables_combined_app_ready.json"
    write_json(combined_path, combined_payload)
    return combined_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Images & Tables shared-ingestion profile.")
    parser.add_argument("--mode", choices=["dry-run", "generate"], default="dry-run")
    parser.add_argument("--input-file", required=True, help="Image file or small folder of image assets.")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--chunk-output", default="")
    parser.add_argument("--output-dir", default="")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = Path(args.input_file).expanduser().resolve()
    limit = max(0, int(args.limit or 0))
    output_stem = input_path.stem if input_path.is_file() else input_path.name
    chunk_output = Path(args.chunk_output).expanduser().resolve() if args.chunk_output else (
        OUTPUT_DIR / f"{output_stem.replace(' ', '_')}_images_tables_normalized_chunks.json"
    )
    app_ready_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else APP_READY_DIR
    started_at = time.time()
    emit("images_tables_profile_start", inputPath=str(input_path), mode=args.mode, limit=limit)
    shared = run_shared_chunk_pipeline(
        source_type=SOURCE_TYPE,
        input_path=input_path,
        output_path=chunk_output,
        limit=limit,
    )
    report = shared["report"]
    bundle = shared["bundle"]
    emit(
        "images_tables_normalized_chunks",
        outputPath=str(chunk_output),
        chunkCount=report.get("chunkCount", 0),
        imageRefCount=report.get("imageRefCount", 0),
        tableRefCount=report.get("tableRefCount", 0),
        classificationSummary=classification_summary(bundle),
        warnings=report.get("warnings", []),
        errors=report.get("errors", []),
    )
    if not report.get("ok"):
        emit("images_tables_profile_complete", ok=False, error="Shared normalized chunk validation failed.", report=report)
        return 1
    output_path = ""
    output_paths: list[str] = []
    validation_errors: list[str] = []
    live_summary: dict[str, Any] = {}
    if args.mode == "generate":
        live_output_root = (
            Path(args.output_dir).expanduser().resolve()
            if args.output_dir
            else (JOB_OUTPUT_ROOT / "images-tables-question-generator" if JOB_OUTPUT_ROOT else PROJECT_ROOT / "tools" / "images-tables-question-generator")
        )
        emit("images_tables_downstream_start", outputRoot=str(live_output_root), inputPath=str(input_path))
        try:
            live_summary = run_images_tables_generator_live(input_path, live_output_root)
        except Exception as exc:
            failure_report = {
                "schemaVersion": "images-tables-profile-runner-report-v1",
                "sourceType": SOURCE_TYPE,
                "mode": args.mode,
                "inputPath": str(input_path),
                "normalizedChunkPath": str(chunk_output),
                "warnings": report.get("warnings", []),
                "validationErrors": [],
                "errors": [str(exc)],
                "ok": False,
            }
            failure_report["recovery"] = recovery_metadata(
                source_type=SOURCE_TYPE,
                outcome="failed_fatal",
                warnings=failure_report["warnings"],
                fatal_errors=failure_report["errors"],
            )
            emit("images_tables_profile_complete", ok=False, error=str(exc), report=failure_report)
            return 1
        combined_path = str(live_summary.get("combinedAppReadyOutputPath") or "")
        output_path = combined_path
        output_paths = [combined_path] if combined_path else []
        emit("images_tables_downstream_complete", ok=True, summary=live_summary)
    total_runtime = round(time.time() - started_at, 3)
    final_report = {
        "schemaVersion": "images-tables-profile-runner-report-v1",
        "sourceType": SOURCE_TYPE,
        "mode": args.mode,
        "inputPath": str(input_path),
        "normalizedChunkPath": str(chunk_output),
        "normalizedChunkCount": report.get("chunkCount", 0),
        "imageRefCount": report.get("imageRefCount", 0),
        "tableRefCount": report.get("tableRefCount", 0),
        "classificationSummary": classification_summary(bundle),
        "outputPath": output_path,
        "outputPaths": output_paths,
        "downstreamSummary": live_summary,
        "runtimeSeconds": total_runtime,
        "warnings": report.get("warnings", []),
        "validationErrors": validation_errors,
        "ok": True,
    }
    final_report["recovery"] = recovery_metadata(
        source_type=SOURCE_TYPE,
        outcome="completed",
        candidate_question_count=int(live_summary.get("filesSucceeded") or 0) if args.mode == "generate" else 0,
        warnings=final_report["warnings"],
        fatal_errors=validation_errors,
        survivors_import_safe=bool(output_paths),
        retry_from_scratch_required=False,
    )
    emit("images_tables_profile_complete", ok=True, report=final_report, outputs=output_paths)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
