#!/usr/bin/env python3
"""
Images & Tables shared-ingestion profile runner.

This milestone is attachment-first. It emits normalized image/table chunks and
creates lightweight app-ready cards that preserve assets, OCR text, and
provenance without semantic question generation.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import json
import mimetypes
import os
import sys
import time
from pathlib import Path
from typing import Any

from chunk_pipeline import run_shared_chunk_pipeline
from recovery_contract import recovery_metadata


RUNNER_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = RUNNER_DIR.parents[1]
JOB_OUTPUT_ROOT = Path(os.environ["BIC_JOB_OUTPUT_ROOT"]).expanduser().resolve() if os.environ.get("BIC_JOB_OUTPUT_ROOT") else None
OUTPUT_DIR = JOB_OUTPUT_ROOT / "shared-ingestion" if JOB_OUTPUT_ROOT else RUNNER_DIR / "output"
APP_READY_DIR = (
    JOB_OUTPUT_ROOT / "images-tables-question-generator" / "output_json" / "app_ready"
    if JOB_OUTPUT_ROOT else PROJECT_ROOT / "tools" / "images-tables-question-generator" / "output_json" / "app_ready"
)
SOURCE_TYPE = "images_tables_source"
OUTPUT_SCHEMA_VERSION = "nbme-internal-app-ready-v2"
LABELS = ["A", "B", "C", "D"]


def emit(event_type: str, **payload: Any) -> None:
    event = {
        "type": event_type,
        "timestamp": dt.datetime.now(dt.timezone.utc).isoformat(),
        **payload,
    }
    print(json.dumps(event, ensure_ascii=False), flush=True)


def now_stamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d_%H%M%S")


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def mime_for(path: Path) -> str:
    return mimetypes.guess_type(path.name)[0] or "application/octet-stream"


def data_url(path: Path) -> str:
    mime = mime_for(path)
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def resolve_project_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def first_image_ref(chunk: dict[str, Any]) -> dict[str, Any]:
    refs = chunk.get("imageRefs") if isinstance(chunk.get("imageRefs"), list) else []
    for ref in refs:
        if isinstance(ref, dict):
            return ref
    return {}


def first_table_ref(chunk: dict[str, Any]) -> dict[str, Any]:
    refs = chunk.get("tableRefs") if isinstance(chunk.get("tableRefs"), list) else []
    for ref in refs:
        if isinstance(ref, dict):
            return ref
    return {}


def classification_label(kind: str) -> str:
    labels = {
        "table_image": "table",
        "algorithm": "algorithm",
        "chart": "chart",
        "stem_image": "image",
        "explanation_image": "image",
        "unknown": "image",
    }
    return labels.get(kind, "image")


def build_lightweight_question(chunk: dict[str, Any], index: int, bundle: dict[str, Any]) -> dict[str, Any]:
    image_ref = first_image_ref(chunk)
    table_ref = first_table_ref(chunk)
    kind = str(image_ref.get("kind") or chunk.get("metadata", {}).get("assetKind") or "unknown")
    asset_path = str(image_ref.get("path") or table_ref.get("path") or "")
    resolved_asset = resolve_project_path(asset_path)
    if not asset_path or not resolved_asset.exists():
        raise FileNotFoundError(f"Q{index}: asset file not found for chunk {chunk.get('chunkId')}: {asset_path}")
    ocr_text = str(chunk.get("text") or image_ref.get("text") or "").strip()
    asset_label = classification_label(kind)
    stem = (
        f"Review the attached {asset_label}. Which statement best describes the source asset preserved by this Images & Tables import card?"
    )
    if ocr_text:
        stem += f"\n\nOCR text preserved for review: {ocr_text[:600]}"
    choices = [
        {"l": "A", "t": "This card preserves the source asset and OCR/provenance for app review."},
        {"l": "B", "t": "This card was generated by advanced semantic medical reasoning."},
        {"l": "C", "t": "This card intentionally discards the original image after import."},
        {"l": "D", "t": "This card bypasses the app-ready JSON import pathway."},
    ]
    image_entry = {
        "figureKey": None,
        "dataUrl": data_url(resolved_asset),
        "isLabTable": kind == "table_image" or chunk.get("chunkType") == "table",
        "kind": "figure",
        "source": "images-tables-shared-ingestion",
        "originalFileName": chunk.get("metadata", {}).get("originalFileName") or resolved_asset.name,
        "assetPath": asset_path,
        "classification": kind,
        "stimulusType": kind,
        "placement": "stem",
        "attachmentConfidence": chunk.get("metadata", {}).get("attachmentConfidence"),
    }
    explanation = (
        "This is an attachment-first validation card. It proves that the normalized image/table asset, OCR text, "
        "and provenance can become an app-ready question and survive import."
    )
    answer_choices = [{"label": item["l"], "text": item["t"]} for item in choices]
    provenance = {
        "sourceType": SOURCE_TYPE,
        "sourceFormat": "images-tables-shared-ingestion",
        "sourceMode": "shared_normalized_chunks",
        "bundleSourcePath": bundle.get("sourcePath"),
        "chunkId": chunk.get("chunkId"),
        "chunkType": chunk.get("chunkType"),
        "assetKind": kind,
        "classificationReason": chunk.get("metadata", {}).get("classificationReason"),
        "attachmentConfidence": chunk.get("metadata", {}).get("attachmentConfidence"),
        "ocrTextAvailable": bool(ocr_text),
        "figureAttachments": {},
    }
    return {
        "id": f"images_tables_profile_{index:03d}_{chunk.get('chunkId')}",
        "questionNumber": index,
        "sourceQuestionNumber": index,
        "stem": stem,
        "answerChoices": answer_choices,
        "correctAnswer": "A",
        "explanationSections": [{"heading": "Attachment Validation", "body": [explanation]}],
        "hasEmbeddedFigure": False,
        "figureRefs": [],
        "tables": [],
        "extractionWarnings": list(chunk.get("warnings") or []),
        "n": index,
        "t": stem,
        "o": choices,
        "c": "A",
        "explanation": explanation,
        "correctBlurb": explanation,
        "e": {},
        "tags": [f"images-tables-{kind}"],
        "retrievalTag": f"images-tables-{kind}",
        "reviewPearl": "Attachment-first card preserving image/table source material for review.",
        "educationalObjective": "Validate image/table attachment preservation and rendering before semantic generation.",
        "images": [image_entry],
        "explanationImages": [],
        "metadata": provenance,
    }


def build_app_ready_payload(bundle: dict[str, Any], input_path: Path) -> dict[str, Any]:
    questions = [
        build_lightweight_question(chunk, index, bundle)
        for index, chunk in enumerate(bundle.get("chunks") or [], start=1)
        if isinstance(chunk, dict)
    ]
    if not questions:
        raise ValueError("No normalized chunks available for app-ready card generation.")
    return {
        "schemaVersion": OUTPUT_SCHEMA_VERSION,
        "name": f"Images Tables Shared Ingestion {now_stamp()}",
        "sourceFormat": "images-tables-shared-ingestion",
        "expectedQuestionCount": len(questions),
        "actualExtractedQuestionCount": len(questions),
        "imageAttachmentStrategy": "Attachment-first q.images[] cards persisted through FigureStore.",
        "metadata": {
            "sourceType": SOURCE_TYPE,
            "sourcePath": str(input_path),
            "normalizedChunkPath": "",
            "generationStyle": "attachment_first",
        },
        "generationWarnings": list(bundle.get("warnings") or []),
        "questions": questions,
    }


def validate_app_ready_payload(payload: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    questions = payload.get("questions")
    if not isinstance(questions, list) or not questions:
        return ["No questions were generated."]
    for index, question in enumerate(questions, start=1):
        prefix = f"Q{index}"
        if question.get("questionNumber") != index:
            errors.append(f"{prefix}: invalid questionNumber.")
        if not question.get("stem") or not question.get("t"):
            errors.append(f"{prefix}: missing stem.")
        if not isinstance(question.get("answerChoices"), list) or len(question["answerChoices"]) != 4:
            errors.append(f"{prefix}: answerChoices must contain four choices.")
        if not isinstance(question.get("o"), list) or len(question["o"]) != 4:
            errors.append(f"{prefix}: compact choices must contain four choices.")
        if question.get("correctAnswer") != "A" or question.get("c") != "A":
            errors.append(f"{prefix}: expected correct answer A.")
        images = question.get("images")
        if not isinstance(images, list) or len(images) != 1:
            errors.append(f"{prefix}: expected exactly one stem image.")
        elif not images[0].get("dataUrl") or not images[0].get("assetPath"):
            errors.append(f"{prefix}: image is missing dataUrl or assetPath.")
    return errors


def classification_summary(bundle: dict[str, Any]) -> dict[str, int]:
    summary: dict[str, int] = {}
    for chunk in bundle.get("chunks") or []:
        if not isinstance(chunk, dict):
            continue
        kind = str(chunk.get("metadata", {}).get("assetKind") or "unknown")
        summary[kind] = summary.get(kind, 0) + 1
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Images & Tables shared-ingestion profile.")
    parser.add_argument("--mode", choices=["dry-run", "generate"], default="dry-run")
    parser.add_argument("--input-file", required=True, help="Image file or small folder of image assets.")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--chunk-output", default="")
    parser.add_argument("--output-dir", default="")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = Path(args.input_file).expanduser().resolve()
    limit = max(0, int(args.limit or 0))
    output_stem = input_path.stem if input_path.is_file() else input_path.name
    chunk_output = Path(args.chunk_output).expanduser().resolve() if args.chunk_output else (
        OUTPUT_DIR / f"{output_stem.replace(' ', '_')}_images_tables_normalized_chunks.json"
    )
    app_ready_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else APP_READY_DIR
    started_at = time.time()
    emit("images_tables_profile_start", inputPath=str(input_path), mode=args.mode, limit=limit)
    shared = run_shared_chunk_pipeline(
        source_type=SOURCE_TYPE,
        input_path=input_path,
        output_path=chunk_output,
        limit=limit,
    )
    report = shared["report"]
    bundle = shared["bundle"]
    emit(
        "images_tables_normalized_chunks",
        outputPath=str(chunk_output),
        chunkCount=report.get("chunkCount", 0),
        imageRefCount=report.get("imageRefCount", 0),
        tableRefCount=report.get("tableRefCount", 0),
        classificationSummary=classification_summary(bundle),
        warnings=report.get("warnings", []),
        errors=report.get("errors", []),
    )
    if not report.get("ok"):
        emit("images_tables_profile_complete", ok=False, error="Shared normalized chunk validation failed.", report=report)
        return 1
    output_path = ""
    validation_errors: list[str] = []
    if args.mode == "generate":
        payload = build_app_ready_payload(bundle, input_path)
        payload["metadata"]["normalizedChunkPath"] = str(chunk_output)
        validation_errors = validate_app_ready_payload(payload)
        if validation_errors:
            failure_report = {
                "schemaVersion": "images-tables-profile-runner-report-v1",
                "sourceType": SOURCE_TYPE,
                "mode": args.mode,
                "inputPath": str(input_path),
                "normalizedChunkPath": str(chunk_output),
                "warnings": report.get("warnings", []),
                "validationErrors": validation_errors,
                "errors": validation_errors,
                "ok": False,
            }
            failure_report["recovery"] = recovery_metadata(
                source_type=SOURCE_TYPE,
                outcome="failed_fatal",
                warnings=failure_report["warnings"],
                fatal_errors=validation_errors,
            )
            emit("images_tables_profile_complete", ok=False, error="App-ready validation failed.", report=failure_report, errors=validation_errors)
            return 1
        app_ready_dir.mkdir(parents=True, exist_ok=True)
        out_path = app_ready_dir / f"images_tables_shared_{now_stamp()}_app_ready.json"
        write_json(out_path, payload)
        output_path = str(out_path.resolve())
    total_runtime = round(time.time() - started_at, 3)
    final_report = {
        "schemaVersion": "images-tables-profile-runner-report-v1",
        "sourceType": SOURCE_TYPE,
        "mode": args.mode,
        "inputPath": str(input_path),
        "normalizedChunkPath": str(chunk_output),
        "normalizedChunkCount": report.get("chunkCount", 0),
        "imageRefCount": report.get("imageRefCount", 0),
        "tableRefCount": report.get("tableRefCount", 0),
        "classificationSummary": classification_summary(bundle),
        "outputPath": output_path,
        "runtimeSeconds": total_runtime,
        "warnings": report.get("warnings", []),
        "validationErrors": validation_errors,
        "ok": True,
    }
    final_report["recovery"] = recovery_metadata(
        source_type=SOURCE_TYPE,
        outcome="completed",
        candidate_question_count=len(bundle.get("chunks") or []) if args.mode == "generate" else 0,
        warnings=final_report["warnings"],
        fatal_errors=validation_errors,
        survivors_import_safe=bool(output_path),
        retry_from_scratch_required=False,
    )
    emit("images_tables_profile_complete", ok=True, report=final_report, outputs=[output_path] if output_path else [])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
